numeros = [8,0,6,10,2,4]
numeros.sort()
print(numeros)
numeros.append(12)
print(numeros)
numeros.insert(0,14)
print(numeros)
numeros.pop(5)
print(numeros)
print(numeros.count(8))
numeros.reverse()
print(numeros)
numeros.remove(12)
print(numeros)
print(len(numeros))